server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:recharge
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
service:
  url-local: http://localhost
  validation:
    port: 8083
  auth:
    port: 8084
  endpoints:
    validate: /api/v1/numcellphone/validation/
    auth-filter: /auth/v1/client/validate
        
        